alter procedure alfa_usp_Sugerido_Picking_Seleccionar_Ruta
@IdPicking  INT,
@ORDEN   INT,
@FILTRO VARCHAR(50),
@TIPO VARCHAR(50)
AS
 SET @FILTRO = CASE
                WHEN @FILTRO = '' THEN @FILTRO
                ELSE @FILTRO + '.'
    END
     CREATE TABLE #SUGTEMP
  ( ID_PICKING INT,ORDEN INT,ID_UBICACION VARCHAR(500),
  ITEMPEDIDO INT,ID_ARTICULO VARCHAR(50),MST_PACK INT,
  CANT_MASTERPACK INT,CANT_UND INT,CANT_TOT_EN_UND INT,
  PICK INT,UBIC_OK BIT,PICK_OK BIT,ID_UBICACION_NEW VARCHAR(500),
  ID_PICADOR VARCHAR(50));
 INSERT INTO #SUGTEMP
 EXEC alfa_usp_Sugerido_Picking_SUG_Filtrado @IdPicking, @TIPO
 SELECT *
 FROM (
  SELECT ID_PICKING,
  ORDEN,
  ID_UBICACION,
  ITEMPEDIDO,
  ID_ARTICULO,
  ITEMDESC,
  CANT_TOT_EN_UND,
  CANT_MASTERPACK,
  MST_PACK,
  PICK,
  'LOTE_INICIAL' 'ID_LOTE2',
  ROW_NUMBER() OVER (ORDER BY ORDEN) AS row_num,
  ISNULL((SELECT TOP 1 ID_LOTE FROM ALFA_TB_PEDIDO_PICKING_RUTA R2 WHERE R2.ID_PICKING = @IdPicking AND R2.ITEMPEDIDO = RUTA.ITEMPEDIDO AND R2.ID_ARTICULO = RUTA.ID_ARTICULO), '') AS ID_LOTE
  FROM #SUGTEMP RUTA
  LEFT JOIN IV00101 IV ON RUTA.ID_ARTICULO = IV.ITEMNMBR   COLLATE Latin1_General_CI_AS
  WHERE ID_PICKING=@IdPicking AND
  RUTA.ID_UBICACION like @FILTRO+'%'
 ) AS ruta_enumerada WHERE row_num = @ORDEN;
 drop table #SUGTEMP

  